---
title: "Class17"
format: pdf
author: "Sabrina Koldinger (A16368238)"
editor: visual
---

# Class 17

```{r}
library(tximport)
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples
```

```{r}
txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
head(txi.kallisto$counts)
```

```{r}
colSums(txi.kallisto$counts)
```

```{r}
sum(rowSums(txi.kallisto$counts)>0)
```

```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```


Principle Component Analysis

```{r}
pca <- prcomp(t(x), scale=TRUE)
summary(pca)
```
Plots

```{r}
plot(pca$x[,1], pca$x[,2], xlab="PC1", ylab="PC2")
     
```



PC1 vs. PC2
```{r}
library(ggplot2)
library(ggrepel)
pcares <- as.data.frame(pca$x)
condition = factor(c("control", "control", "treatment","treatment"))
ggplot(pcares)+ aes(x=PC1,y=PC2, col=condition) + geom_point() +
  geom_text_repel(label=rownames(pcares)) +labs(title= "PC1 vs. PC2")
```



PC2 vs. PC3
```{r}
ggplot(pcares)+ aes(x=PC2,y=PC3, col=condition) + geom_point() +
  geom_text_repel(label=rownames(pcares)) +labs(title= "PC2 vs. PC3")
```



PC1 vs. PC3
```{r}
ggplot(pcares)+ aes(x=PC1,y=PC3, col=condition) + geom_point() +
  geom_text_repel(label=rownames(pcares))+labs(title= "PC1 vs. PC3")
```

